NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [ ]:
import numpy as np
arr = np.array(42) # 0D array
a=np.array([1,3,5,7]) # 1D array
b=np.array([[2,6,8,10],[1,2,3,4]]) # 2D array (an array containing two 1D arrays)
c=np.array([[[1,2,3,4],[2,4,6,8]],[[7,6,4,3],[2,4,9,6]]]) # 3D array (an array containing two 2D arrays)

# to check the dimension of the array <array>.ndim
print(arr.ndim) 
print(a.ndim)
print(b.ndim)
print(c.ndim)

# Access the element on the first row, second column:
print("2nd element on 1st row: ", b[0, 1])
#Access the fourth element of the second array of the first array:
print("4th element of the second array of the first array: ",c[0,1,3])

# shape of the array <array>.shape
print(arr.shape)
print(a.shape)
print(b.shape) 
print(c.shape)

# Printing type of elements in array <array>.dtype
print(arr.dtype)
print(a.dtype)

#Creating a nXm array with all zeros: array=np.zeros(n,m)
i=np.zeros((3,3)) 
print(i)

#Creating a nXm array with all ones: array=np.ones(n,m)
j=np.ones((4,4))
print(j)

#Create a array of dimension nXm having constant value x: array=np.full((n,m),x)

array=np.full((3,4),5) # n represents the number of rows in the matrix, m is the number of columns, x is the constant value.
print(array)

# Creating array from list with type float
d=np.array([1,2,3,4],dtype=float)
print(d)

# Create an array with random values
e=np.random.random((2,2,3))
print(e)

#Create a sequence of integers from n to m with step x: np.arange(n,m,x) 
f=np.arange(0,30,5)
print(f)

# Create a sequence of 10 values in range 0 to 5
# linspace returns evenly spaced values within a given interval. num no. of elements are returned.
g = np.linspace(0,5,10)
print(g)

# reshaping array <array>.reshape 
g = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
newarr = g.reshape(2, 2, 3)
print(newarr)

# Flatten array
# We can use flatten method to get a copy of array collapsed into one dimension.
h = np.array([[1, 2, 3], [4, 5, 6]])
flarr = h.flatten()

In [ ]:
# Array Slicing
# We pass slice instead of index like this: [start:end]. We can also define the step, like this: [start:end:step].
# slicing 1D array 
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[1:5:2])
print(arr[::2])

# slicing 2D array
b=np.array([[2,6,8,10],[1,2,3,4]])
print(b[1,1:3])
print(b[0:2,2]) # From both elements, return index 2

# boolean array
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

NumPy Array Copy

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [36]:
arr = np.array([1,2,3,4])
x = arr.copy() # Make a copy
arr[0]=15  # change the original array
print(arr)
print(x)

[15  2  3  4]
[1 2 3 4]


NumPy Array View

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [38]:
arr = np.array([1, 2, 3, 4])
x=arr.view() # view
arr[0]=15 #change the original array -> affects the view
x[1]=20 #change the view array -> affects the original array
print(arr)
print(x)

[15 20  3  4]
[15 20  3  4]
